excluded_legal_forms <- c('Limited liability partnership',
                         'Non statutory partnership - BGB',
                         'Foundation & partnership',
                         'Foreign company',
                         'Public limited partnership - AG & Co. KG',
                         'Registered cooperative - eG',
                         'Registered cooperative & partnership - eG & Co. KG',
                         'European company - SE',
                         'Entrepreneurial company (limited liability) & partnership by shares - UG & Co. KGaA',
                         'Association - Verein',
                         'Limited partnership by shares - KGaA',
                         'Institution under public law',
                         'Liberal profession',
                         'Mutual insurance company - VVaG',
                         'Civil right partnership - GbR',
                         'Public utility',
                         'Legal entity of public law',
                         'Cooperative company',
                         'European cooperative company - SCE',
                         'Partnership',
                         'Public authority',
                         'Foundation',
                         'PartG mbB',
                         'Limited partnership & partnership - KG & Co. KG',
                         'Private foundation',
                         'European economic interest group - EWIV',
                         'Limited liability company & partnership by shares - GmbH & Co. KGaA',
                         'Association & partnership - Verein & Co. KG',
                         'Non profit limited liability company',
                         'Entrepreneurial company (limited liability) & partnership - UG & Co. KG',
                         'Civil right company - GbR',
                         'Registered association - eV',
                         'Joint stock company',
                         'Public corporation',
                         'Commercial enterprise',
                         'Registered individual business - e.U.',
                         'Entrepreneurial company (limited liability) - UG'
)
